# Importando librería nunmpy

In [1]:
import numpy as np

#### creando una lista de 10 elementos

In [3]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la Lista a un Array

In [5]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Compropbando el tipo de estructura

In [6]:
type(arreglo)

numpy.ndarray

#### comprobando el tipo de dato

In [8]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [9]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### sigue siendo un array de int32

In [10]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Transformando el Array de int32 a float32 (transformar no es lo mismo que definir)

In [11]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Fincion similar a Range pero ocupando Arrays (arreglos) / (arange, es exculusivo para trabajar con "arrays")

In [12]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### numeros impares

<h4 style = "color:lightblue"><b> FUNCIONES DE NUMPY<b></h4>

<h4 style = "color:Hotpink"> Obteniendo el promedio del array</h3>

In [13]:
promedio = np.mean(arreglo)
promedio

5.5

#### obteniendo la mediana

In [15]:
mediana = np.median(arreglo)
mediana

5.5

#### obteniendo desviacion estandar

In [16]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

#### Generacion de un arreglo de 10 elementos de solo "unos"

In [17]:
arreglos_de_unos = np.ones(10)
arreglos_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arreglos_de_ceros = np.zeros(10)
arreglos_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arreglos_int_unos = arreglos_de_unos.astype(int)
arreglos_int_unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# UTILIZANDO FUNCIÓN RANDOM

#### arreglo aleatorio de 5 elementos

arre

In [20]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.93490951, 0.66609841, 0.12389242, 0.12058134, 0.01905206,
       0.1266476 , 0.49959134, 0.86159772, 0.56488222, 0.69454414])

In [21]:
matriz = np.random.rand(3,3)
matriz

array([[0.99403526, 0.92474059, 0.86894767],
       [0.02604641, 0.54958768, 0.55180234],
       [0.32232335, 0.88251308, 0.83417836]])

In [23]:
arreglo_aleatorio2 = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([790,  28, 841, 197, 779, 497, 841,  25, 724, 688])

In [43]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[72, 29, 65, 79, 79, 76, 59, 40, 99, 19],
       [20, 68, 20, 35, 65, 85, 66, 89, 74, 67],
       [64, 22, 85, 21, 35, 74, 71, 64,  3, 38],
       [10, 53, 31, 94, 12, 14, 66, 48, 12, 15],
       [83, 33, 96, 46, 61, 18, 20, 86, 55, 21],
       [89, 38, 67, 98, 68, 40, 51, 79, 52, 31],
       [71, 12, 81, 86,  2, 88, 18, 93, 29, 12],
       [ 1, 26, 47, 65, 39, 63, 99, 12,  3,  5],
       [35, 97,  3, 43, 56, 17, 86, 28, 19, 40],
       [54, 64, 35, 99, 12, 79, 37, 45, 48, 19]])