# Ej 1 de laboratorio

#### A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos del 1 al 10. Este array no debe ser aleatorio. (listo) 

In [39]:
#importar biblioteca

import numpy as np

In [40]:
# Creando el array de 10 numeros consecutivos
elementos = np.arange(1,11)
elementos #tiene del 1 al 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores deben ser enteros entre el 1 al 20. (listo) 

In [41]:
elementos2 = np.random.randint(1,21,10)
elementos2 # tiene elementos desordenados del 1 al 20

array([19, 20, 10, 10,  3, 14, 12, 20,  9, 19])

#### C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores (listo)

In [42]:
suma_vectores = elementos + elementos2
suma_vectores # la suma de ambos

array([20, 22, 13, 14,  8, 20, 19, 28, 18, 29])

#### D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV. (listo)

In [43]:
np.random.shuffle(suma_vectores)
suma_vectores

array([13, 19,  8, 20, 29, 18, 22, 20, 14, 28])

### E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando las funciones vistas en la Unidad IV. Tomar el vector de la letra D. (listo)

##### mediana)


In [44]:
print(f"la mediana es: {np.median(suma_vectores)}")

la mediana es: 19.5


##### promedio)

In [45]:
print(f"El promedio es: {np.mean(suma_vectores)}")

El promedio es: 19.1


##### posición de valor Máximo)

In [46]:
print(f"la posición del valor Máximo es: {np.argmax(suma_vectores)}")

la posición del valor Máximo es: 4


##### Posición del valor Mínimo)

In [47]:
print(f"La posición del valor Mínimo es: {np.argmin(suma_vectores)}")

La posición del valor Mínimo es: 2


### F. Transformar el vector obtenido en una Matriz de 2 x 5 (listo)

In [51]:
# transformando a matriz

matriz = np.reshape(suma_vectores,(2,5))
matriz

array([[13, 19,  8, 20, 29],
       [18, 22, 20, 14, 28]])